name: Build Arcaflow Python Wheel
on: 
  push:
    tags:
      - v*
jobs:
  build:
    name: "Build Arcaflow Python Wheel"
    runs-on: ubuntu-latest
    steps:
      - name: version format check
        if: startsWith(github.event.ref, 'refs/tags/')
        shell: bash
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          [[  ${VERSION//[[:blank:]]/} =~ ^v[[:digit:]]+\.[[:digit:]]\.[[:digit:]]$ ]] && export OK="[INF] version format accepted" 
          [[ -z $OK ]] && echo "[ERR] wrong version format: $VERSION" && exit 1
          echo $OK
      - name: Check out code
        uses: actions/checkout@v3
      - name: cd 
        run: |
          cd arcaflow
      - name: ls
        run: | 
          ls -al

      #- name: Install Python
      #  uses: actions/setup-python@v4
      #  with:
      #    python-version: '3.9'
      #    architecture: 'x64'
      #- name: Build the wheel (arcaflow)
      #  env:
      #    RELEASE_VERSION: v0.1.0
      #  shell: bash
      #  run: |
      #    make -v
      #    bash --version
      #    echo $SHELL
      #    make setup
      #    sed -ri "s/^(.+version=')(.+)('.*)/\1${RELEASE_VERSION/v/}\3/g" setup.py
      #    make build_linux_amd64
      #    make build_linux_arm64
      #    make build_darwin_amd64
      #    make build_darwin_arm64
      #    make build_windows_amd64
      #    twine upload --verbose --skip-existing --repository testpypi -u ${{secrets.PYPI_USER}} -p ${{secrets.PYPI_PASS}} --non-interactive dist/*