name: Build Arcaflow Python Wheel
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Build the project
        env:
          RELEASE_VERSION: v0.1.0
        shell: bash
        run: |
          make -v
          bash --version
          echo $SHELL
          make setup
          sed -ri "s/^(.+version=')(.+)('.*)/\1${RELEASE_VERSION/v/}\3/g" setup.py
          make build_linux_amd64
          make build_linux_arm64
          make build_darwin_amd64
          make build_darwin_arm64
          twine upload --repository testpypi -u ${{secrets.PYPI_USER}} -p ${{secrets.PYPI_PASS}} --non-interactive dist/*